#pragma once

#include <span>
#include <array>

#include "mesh/SimpleMesh.h"
#include "mesh/utils.h"
#include "octree/Storage.h"
#include "octree/traverse.h"
#include "octree/NodeStatus.h"
#include "octree/Space.h"
#include "log.h"

inline SimpleMesh merge_meshes(
    const SimpleMesh& mesh1, // base mesh
    const SimpleMesh& mesh2  // priority mesh
) {
    if (mesh1.is_empty()) {
        return mesh2;
    }
    if (mesh2.is_empty()) {
        return mesh1;
    }

    // TODO: actual merge
    return mesh2;
}

inline std::optional<std::array<octree::NodeAndId, 8>> split_mesh_into_children(const octree::NodeAndId& node) {
    if (!node.id.has_children()) {
        return std::nullopt;
    }

    const auto space = octree::Space::earth(); // TODO: store in storage

    const auto children = node.id.children().value();
    std::array<octree::NodeAndId, children.size()> child_nodes;
    for (size_t i = 0; i < children.size(); i++) {
        const auto& child_id = children[i];
        const auto child_bounds = space.get_node_bounds(child_id);
        const auto child_mesh = clip_mesh_on_bounds(node.node, child_bounds);
        child_nodes[i] = {child_id, std::move(child_mesh)};
    }
    return child_nodes;
}

struct MergeState {
    octree::Storage& output;
    const octree::Storage& input;
    const octree::IndexMap& output_index;
    const octree::IndexMap& input_index;
};

inline void merge_leaves(
    MergeState& state,
    const octree::Id& id
) {
    LOG_INFO("Merging leaves for id: {}", id);

    assert(state.output_index.is(octree::NodeStatus::Leaf, id));
    assert(state.input_index.is(octree::NodeStatus::Leaf, id));
    const auto output_mesh = state.output.read_node(id).value();
    const auto input_mesh = state.input.read_node(id).value();
    SimpleMesh merged_mesh = merge_meshes(
        output_mesh,
        input_mesh
    );
    state.output.write_node(id, merged_mesh);
}

inline void merge_with_leaf(
    MergeState &state,
    const octree::Id &id,
    const SimpleMesh &leaf_mesh,
    bool leaf_is_output, // true if leaf is from output, false if from input
    bool leaf_is_clipped // true if the leaf mesh was generated by clipping
) {
    LOG_INFO("Merging leaf from {} for id: {}", 
        leaf_is_output ? "output" : "input", 
        id
    );

    if (leaf_is_output) {
        if (leaf_is_clipped) {
            assert(state.output_index.is_absent(id));
        } else {
            assert(state.output_index.is(octree::NodeStatus::Leaf, id));
        }
        assert(state.input_index.is(octree::NodeStatus::Virtual, id));
    } else {
        if (leaf_is_clipped) {
            assert(state.input_index.is_absent(id));
        } else {
            assert(state.input_index.is(octree::NodeStatus::Leaf, id));
        }
        assert(state.output_index.is(octree::NodeStatus::Virtual, id));
    }
    assert(id.has_children());

    // Split the leaf mesh into children
    const auto leaf_children = split_mesh_into_children({id, leaf_mesh});
    assert(leaf_children.has_value());

    // Merge each child
    for (const auto& child : *leaf_children) {
        const auto& child_id = child.id;
        const auto& child_mesh = child.node;

        // Load other child mesh from the other dataset
        const auto other_status_opt = leaf_is_output
            ? state.input_index.get(child_id)
            : state.output_index.get(child_id);
        if (!other_status_opt.has_value()) {
            // TODO: dont generate meshes for non-existing input nodes
            // If the other child does not exist, we can just write the clipped mesh from the leaf
            state.output.write_node(child_id, child_mesh);
            continue;
        }
        const auto other_status = other_status_opt.value();
        assert(other_status != octree::NodeStatus::Inner);

        if (other_status == octree::NodeStatus::Virtual) {
            // If the other child is virtual, we recurse further
            merge_with_leaf(state, child_id, child_mesh, leaf_is_output, true);
        } else if (other_status == octree::NodeStatus::Leaf) {
            // If the other child is a leaf, we can merge it directly
            SimpleMesh merged_mesh;
            if (leaf_is_output) {
                // If the leaf is from output, we read from input
                const auto other_mesh = state.input.read_node(child_id).value();
                merged_mesh = merge_meshes(child_mesh, other_mesh);
            } else {
                // If the leaf is from input, we read from output
                const auto other_mesh = state.output.read_node(child_id).value();
                merged_mesh = merge_meshes(other_mesh, child_mesh);
            }
            state.output.write_node(child_id, merged_mesh);
        } else {
            UNREACHABLE();
        }
    }
}

inline void copy_subtree_to_output(
    MergeState& state,
    const octree::Id& id
) {
    LOG_INFO("Copying subtree to output for id: {}", id);

    assert(state.input.has_node(id));
    assert(!state.output.has_node(id));

    octree::traverse(
        state.input_index, 
        [&](const octree::Id& child_id, const octree::NodeStatus& status) {
            if (status == octree::NodeStatus::Virtual) {
                return;
            }
            assert(status == octree::NodeStatus::Leaf);
            
            const auto child_mesh = state.input.read_node(child_id).value();
            state.output.write_node(child_id, child_mesh);
        },
        [](const octree::Id &) { return true; },
        id
    );
}

inline void merge_node(
    MergeState& state,
    const octree::Id& id
) {
    LOG_INFO("Merging nodes for id: {}", id);

    const auto output_state_opt = state.output_index.get(id);
    const auto input_state_opt = state.input_index.get(id);

    if (!input_state_opt.has_value()) {
        // If the input does not have the node, we can skip it
        return;
    }
    if (!output_state_opt.has_value()) {
        // If the output does not have the node, we can copy it
        copy_subtree_to_output(state, id);
        return;
    }

    const auto output_status = output_state_opt.value();
    const auto input_status = input_state_opt.value();

    assert(output_status != octree::NodeStatus::Inner);
    assert(input_status != octree::NodeStatus::Inner);

    if (output_status == octree::NodeStatus::Leaf && input_status == octree::NodeStatus::Leaf) {
        // If both nodes are leaves, we can merge them directly
        merge_leaves(state, id);
    } else if (output_status == octree::NodeStatus::Leaf && input_status == octree::NodeStatus::Virtual) {
        merge_with_leaf(state, id, state.output.read_node(id).value(), true, false);
    } else if (output_status == octree::NodeStatus::Virtual && input_status == octree::NodeStatus::Leaf) {
        merge_with_leaf(state, id, state.input.read_node(id).value(), false, false);
    } else if (output_status == octree::NodeStatus::Virtual && input_status == octree::NodeStatus::Virtual) {
        // If both nodes are virtual, recurse
        assert(id.has_children());
        const auto children = id.children().value();
        for (const auto& child_id : children) {
            merge_node(state, child_id);
        }
    } else {
        UNREACHABLE();
    }
}

inline void merge_datasets(octree::Storage& output, const octree::Storage& input) {
    const auto& output_index = output.ensure_indexed();
    const auto& input_index = input.ensure_indexed();

    MergeState state{output, input, output_index, input_index};
    merge_node(state, octree::Id::root());
}

inline void merge_datasets(octree::Storage& output, const std::span<octree::Storage> inputs) {
    for (const auto& input : inputs) {
        merge_datasets(output, input);
    }
}
