# GDAL 3.10 reads the global LRU head outside its cache lock in Touch().
# Compile a patched build-local copy; leave the shared dependency source intact.
function(alp_patch_gdal_block_cache)
    set(_source "${CMAKE_SOURCE_DIR}/gcore/gdalrasterblock.cpp")
    file(READ "${_source}" _contents)
    set(_unlocked_check "    // Can be safely tested outside the lock\n    if (poNewest == this)\n        return;\n\n")
    string(FIND "${_contents}" "${_unlocked_check}" _position)
    if(_position EQUAL -1)
        message(FATAL_ERROR "GDAL block-cache source changed; review the Touch() race patch")
    endif()
    # Touch_unlocked() repeats this check after TAKE_LOCK.
    string(REPLACE "${_unlocked_check}" "" _contents "${_contents}")
    set(_patched "${CMAKE_BINARY_DIR}/alp_patched/gdalrasterblock.cpp")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/alp_patched")
    file(WRITE "${_patched}" "${_contents}")
    get_target_property(_sources gcore SOURCES)
    list(FIND _sources "gdalrasterblock.cpp" _index)
    if(_index EQUAL -1)
        message(FATAL_ERROR "GDAL gcore source list changed; review the block-cache patch")
    endif()
    list(REMOVE_AT _sources ${_index})
    list(APPEND _sources "${_patched}")
    set_property(TARGET gcore PROPERTY SOURCES "${_sources}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_source}")
endfunction()

cmake_language(DEFER CALL alp_patch_gdal_block_cache)
